namePrefix: kustomize-

resources:
- anyuid-binding.yaml  
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- guestbook-ui-route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
